services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - "5000:5000"
    command: uv run flask run --host=0.0.0.0
    stdin_open: true
    tty: true
