name: Setup Python Env

description: Setup Python Env

inputs:
  python-version:
    required: false
    default: 3.12

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Sync dependencies
      run: uv sync --frozen --group dev
      shell: bash
